/**
 * Cronicle Job Setup — Motra Full Gym Sync (Self-Refreshing Auth)
 *
 * Builds a self-contained inline shell-plugin script by embedding
 * scripts/motra_fetch_core.cjs verbatim, then pushes it to Cronicle.
 *
 * Auth flow (never expires unless the user revokes it):
 *   1. embedded Firebase refresh token
 *   2. POST securetoken.googleapis.com -> fresh 60min ID token
 *   3. GET all 8 backend.motra.com endpoints
 *   4. PATCH Firestore api_feeds/motra_metrics via REST
 *
 * Run: node scripts/setup_cronicle_motra_job.cjs
 */

const axios = require('axios');
const fs = require('fs');
const path = require('path');

const CRONICLE_URL = process.env.CRONICLE_URL || 'http://umbrel.local:3012';
const CRONICLE_API_KEY = process.env.CRONICLE_API_KEY || 'ba768ce3fa7125fa071a5e2d62110bd7';
const CRONICLE_EVENT_ID = 'ems1n964g1f';
const FIRESTORE_PROJECT = 'epaper-api-key';

const ACTIVE_HOURS = [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0];
const INTERVAL_MINUTES = [5, 35];

const REFRESH_TOKEN_FILE = path.resolve(__dirname, '..', '.motra_refresh_token');
const REFRESH_TOKEN = fs.existsSync(REFRESH_TOKEN_FILE)
  ? fs.readFileSync(REFRESH_TOKEN_FILE, 'utf8').trim()
  : (process.env.MOTRA_REFRESH_TOKEN || '').trim();

if (!REFRESH_TOKEN) {
  console.error('❌ No refresh token (.motra_refresh_token or MOTRA_REFRESH_TOKEN)');
  process.exit(1);
}
console.log(`✅ Loaded refresh token (${REFRESH_TOKEN.slice(0, 20)}...)`);

// Embed the shared fetch core, minus its module.exports tail.
const corePath = path.resolve(__dirname, 'motra_fetch_core.cjs');
const coreSrc = fs.readFileSync(corePath, 'utf8').split('module.exports')[0].trimEnd();
console.log(`✅ Inlined motra_fetch_core.cjs (${coreSrc.length} chars)`);

/** Convert a plain JS value into a Firestore REST typed value. */
function toFirestoreValue(v) {
  if (v === null || v === undefined) return { nullValue: null };
  if (typeof v === 'boolean') return { booleanValue: v };
  if (typeof v === 'number') {
    return Number.isInteger(v) ? { integerValue: String(v) } : { doubleValue: v };
  }
  if (typeof v === 'string') return { stringValue: v };
  if (Array.isArray(v)) {
    return { arrayValue: { values: v.map(toFirestoreValue) } };
  }
  const fields = {};
  for (const [k, val] of Object.entries(v)) fields[k] = toFirestoreValue(val);
  return { mapValue: { fields } };
}

const inlineScript = `#!/usr/bin/env node
/* Motra Full Gym Sync — generated by setup_cronicle_motra_job.cjs. Do not edit here. */

const REFRESH_TOKEN = ${JSON.stringify(REFRESH_TOKEN)};
const FIRESTORE_URL = "https://firestore.googleapis.com/v1/projects/${FIRESTORE_PROJECT}/databases/(default)/documents/api_feeds/motra_metrics";

${coreSrc}

/* ---- Firestore REST serialisation ---- */
${toFirestoreValue.toString()}

async function run() {
  const now = new Date();
  console.log("📡 Motra Full Gym Sync — " + now.toISOString());

  const tokens = await mintIdToken(REFRESH_TOKEN);
  console.log("🔑 ID token minted for user " + tokens.userId);

  const payload = await fetchAllGymData(tokens.idToken, now.getTime());
  logPayloadSummary(payload);

  if (!payload.meta.endpointsOk.length) {
    throw new Error("All Motra endpoints failed — refusing to overwrite Firestore");
  }

  const body = {
    fields: {
      apiName: { stringValue: "MOTRA" },
      source: { stringValue: "Motra Worker (Cronicle, full gym sync)" },
      timestamp: { timestampValue: now.toISOString() },
      status: { stringValue: "success" },
      payload: toFirestoreValue(payload)
    }
  };

  const res = await fetch(FIRESTORE_URL, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });

  if (!res.ok) {
    throw new Error("Firestore write failed: " + res.status + " " + (await res.text()));
  }
  console.log("✅ Firestore updated: api_feeds/motra_metrics");
}

run().catch(err => {
  console.error("❌ Fatal:", err.message);
  process.exit(1);
});
`;

// Exported so scripts/verify_motra_inline.cjs can check the generated script
// without pushing it to Cronicle.
module.exports = { inlineScript, toFirestoreValue, CRONICLE_EVENT_ID };

async function main() {
  const url = `${CRONICLE_URL}/api/app/update_event/v1?api_key=${CRONICLE_API_KEY}`;

  const event = {
    id: CRONICLE_EVENT_ID,
    title: 'Motra Full Gym Sync',
    enabled: 1,
    category: 'general',
    target: 'allgrp',
    algo: 'random',
    plugin: 'shellplug',
    timing: { hours: ACTIVE_HOURS, minutes: INTERVAL_MINUTES },
    params: { script: inlineScript },
    notes:
      'Pulls all 8 Motra endpoints: weekly stats, workouts, muscle groups, streak, ' +
      'leaderboard, PRs, muscle recovery. Self-refreshing Firebase auth — never expires.',
  };

  console.log(`\n📡 Pushing to Cronicle (${CRONICLE_URL})...`);
  console.log(`   inline script: ${inlineScript.length} chars`);

  try {
    const { data } = await axios.post(url, event);
    if (data.code === 0) {
      console.log('✅ Cronicle event updated: Motra Full Gym Sync');
    } else {
      console.log('⚠️  Cronicle response:', data);
    }
  } catch (err) {
    console.error('❌ Cronicle error:', err.response ? err.response.data : err.message);
    process.exit(1);
  }
}

// Only push when run directly, not when require()'d by the verifier.
if (require.main === module) {
  main();
}
